const fs = require('fs');
const PDFDocument = require('pdfkit');

const doc = new PDFDocument();
doc.pipe(fs.createWriteStream('ML_Output_Format.pdf'));

doc.fontSize(20).font('Helvetica-Bold').text('Neuro-AI ML Pipeline Output Specifications', { align: 'center' });
doc.moveDown();

doc.fontSize(12).font('Helvetica').text("This document outlines the exact data schema and generated output from the Neuro-AI predictive analytics pipeline for a standard user profile. These features are extracted from the user's platform usage and structured to feed into the Machine Learning model.");
doc.moveDown();

doc.fontSize(16).font('Helvetica-Bold').text('Machine Learning Payload Format');
doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica').text('The data extracted from the application layer into the ML input tensor consists of 8 critical features. Below is an example payload representing the current dynamic state of the user.');
doc.moveDown();

const payload = {
  Age: 20,
  Gender: 1,
  LearningStyle: 1,
  StudyHours: 0,
  Attendance: 80,
  OnlineCourses: 5,
  Discussions: 0,
  Internet: 1
};

doc.font('Courier').fontSize(11).text(JSON.stringify(payload, null, 2), {
  indent: 20
});
doc.moveDown();

doc.fontSize(16).font('Helvetica-Bold').text('Feature Breakdown');
doc.moveDown(0.5);

doc.fontSize(12);
doc.font('Helvetica-Bold').text('1. Age (Number)');
doc.font('Helvetica').text('   - The verified age of the student.');
doc.font('Helvetica-Bold').text('2. Gender (Categorical / Integer)');
doc.font('Helvetica').text('   - Extracted gender mapping (e.g., 1 for Male, 0 for Female).');
doc.font('Helvetica-Bold').text('3. LearningStyle (Categorical / Integer)');
doc.font('Helvetica').text('   - Behavioral learning preference (0 Visual, 1 Auditory, 2 Kinesthetic).');
doc.font('Helvetica-Bold').text('4. StudyHours (Number)');
doc.font('Helvetica').text('   - The total aggregated hours the student has spent studying.');
doc.font('Helvetica-Bold').text('5. Attendance (Number / Percentage)');
doc.font('Helvetica').text('   - Calculated interaction percentage (currently defaulting to 80%).');
doc.font('Helvetica-Bold').text('6. OnlineCourses (Number)');
doc.font('Helvetica').text('   - Dynamic count of subjects the student is currently enrolled in.');
doc.font('Helvetica-Bold').text('7. Discussions (Number)');
doc.font('Helvetica').text('   - Weighted engagement within peer discussions.');
doc.font('Helvetica-Bold').text('8. Internet (Boolean / Integer)');
doc.font('Helvetica').text('   - Identifies internet connectivity stability (1 representing continuous).');

doc.moveDown(2);
doc.fontSize(10).font('Helvetica-Oblique').text('Generated by the Neuro-AI Adaptive System Core Framework', { align: 'center' });

doc.end();
console.log("PDF Created in " + process.cwd());
